### ISSUE TITLE
Feature Request: Indentation

### ISSUE THREAD

**Issue by oheydrew** [yatki/vscode-surround#8] opened 2018-09-12 02:42 UTC
Referencing issue #2 (indentation):

Great work on the extension. It'd still be fantastic if we could somehow set the indentation to match the current selection's indentation. I see you've ruled it out as "not being part of the use case" - but I respectfully disagree. 

I've taken your extension and written a few wrappers for ruby methods, and Rspec tests, and it's great!  But I've found when I'm wanting to wrap existing code in existing indentation levels, that it's putting the new wrappers in at indentation 0, and leaving the rest indented as it was.

This isn't ideal as it requires me to highlight and re-indent manually, which I'm beginning to think negates the workflow speed increase for me.

Is it possible to keep the existing indentation level? I could take a look at this if you accept PR's.

**Comment by yatki** [comment] 2018-09-12 16:32
Hey @oheydrew, thank you very much for your message. I'm glad to hear that it's useful for you.

I'm a bit confused because I think extension already should be working as you described. Here, I recorded an example on my pc.
![saq8y-wf7hw](https://user-images.githubusercontent.com/26697004/45439273-a2b86a80-b6b9-11e8-9c6f-42e3bf28bcd0.gif)

Please let me know if I'm missing something.

Could you please share the steps to reproduce the issue and also share
- vscode version
- your snippet config (copy and paste it as it is)
- surround version
- (if possible) also a screenshot of the final result when you wrap the selection.

Thanks.

**Comment by ylc395** [comment] 2019-09-24 13:40
Auto Indentation seems not to work on my PC, too. Does this feature depend on any setting or something?

**Comment by Sti2nd** [comment] 2021-07-18 12:33
Maybe it wouldn't be so hard to implement this 🤔 If one assumes that the existing code is indented correctly, the indent should be the same amount as the indent on the first line.

E.g. in the following image the indent should be 2 spaces, since there are two spaces before the first character
![image](https://user-images.githubusercontent.com/6373430/126064837-b2ba5a37-7c25-4c68-85cb-8fcee66307fb.png)

What do you think about an auto-indent feature implemented this way @yatki ? Should I try to implement this? 😊

**Comment by yatki** [comment] 2021-07-18 18:11
Hey @Sti2nd thank you very much for your message. Did you also experience the same issue? Because it's not an issue with most people. Vs code is able to preserve the indentation automatically.. Could you please record your screen to show me how it happens? Also are you using tab characters or whitespace for tabs? I actually tested the extension with both settings and it was working fine.

If we can determine the root cause of the problem first, I'd appreciate any contribution 🤓👍🏻

**Comment by Sti2nd** [comment] 2021-07-18 19:55
@yatki Here is a video!

https://user-images.githubusercontent.com/6373430/126080387-0dc5f9dc-5ec0-4a50-a83a-e2889edde920.mp4

2 whitespace is the indent in the video. I actually have this code in a [Dev container](https://code.visualstudio.com/docs/remote/containers) so if you can't reproduce I could share the repo with you 🙂

**Comment by yatki** [comment] 2021-07-18 22:41
Thank you very much for your efforts.. Much appreciated. Now i see the problem. So basically when i surround my code blocks i usually only select the text not the whitespaces before the line.. (whitespaces before const in your case). So i never experienced this problem. 😁😅

Maybe if you have time you can try to come up with a solution.. It might not be as straightforward as you think tho because vscode applies the changes on selected text.. There are modifiers for SELECTED_TEXT variable. Maybe you can look into those.. https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples

If you don't have time no worries.. I'll look into it this week otherwise. 🖖🏻

**Comment by Sti2nd** [comment] 2021-07-19 07:26
I won't have time before the weekend, I think. I will post here if I begin to look into it! 😊 Otherwise you can just go ahead and fix it if you have time before me ✌️ 😁

**Comment by yatki** [comment] 2021-07-19 18:20
The issue is resolved in version 1.2.0. Thanks for reporting the issue.

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.2.0)

Cheers 🖖,

**Closed by yatki** 2021-07-19 18:20 UTC

**Comment by Sti2nd** [comment] 2021-07-20 07:52
Thank you, yatki! Good work! 🥇 👏

**Comment by Sti2nd** [comment] 2021-09-16 18:08
I think this bug came back @yatki ? Can you reproduce?

**Comment by yatki** [comment] 2021-09-16 18:13
@Sti2nd which version are you using? Could you please share the code that you are trying to surround?

**Comment by Sti2nd** [comment] 2021-09-16 18:24
Version 1.2.2.

Here is a video

https://user-images.githubusercontent.com/6373430/133665016-5033ed95-ba49-4d5e-8547-ad36f7445620.mp4

**Comment by yatki** [comment] 2021-09-17 20:11
@Sti2nd this is very weird. I am not able to reproduce this issue. Are you using tabs or spaces as whitespace?

**Comment by Sti2nd** [comment] 2021-11-08 21:33
Using spaces @yatki , but it doesn't make any difference 🤷

**Comment by yatki** [comment] 2021-11-08 21:46
That is super weird. I wrote an exact copy of your code just to see if there is a weird character or something that prevents it but it works like a charm in mac and windows.. 

I assume you are using the latest version of vscode right?  Did you try it in different files or on different code blocks? What is the encoding of the file? 

The only problem I can think of a hidden character is messing up the whitespace. Because the script is trimming all the whitespace until the first non-whitespace char. And puts the surrounding block in that position. If trimming fails, the problem you are having would happen.

So maybe highlighting whitespace chars as "." could help you to identify the problem.

Let me know if this helps..

**Comment by Sti2nd** [comment] 2021-11-08 22:01
Tried in another project as well since I thought it might be because of the DEV container environment, but got the same result in a "regular" TS project. I will try to make time to test in different environments, but can't promise anything.

I have VS Code 1.62.0 User setup; extension is v1.2.2; input language in Windows is set to English with Norwegian keyboard.
When you try to reproduce you mark the whole line from the beginning of the window, right, and not only the beginning of the text inside the window.
